debug: true

spring:
  application:
    name: user-service

logging:
    level:
        org:
            springframework:
                security: DEBUG
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
    user:
        password: password
server:
    contextPath: /uaa
    port: 9999
